<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons [
    <!ELEMENT lastname (#PCDATA)>
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT residence (#PCDATA)>
    <!ELEMENT children (person*)>
    <!ELEMENT person (firstname, (lastname?), (children?), (residence?))>
    <!ELEMENT persons (person+)>
    <!ATTLIST person id ID #REQUIRED>
    <!ATTLIST person friends IDREFS #IMPLIED>
	<!ATTLIST persons file CDATA #IMPLIED>
    ]>
<?mach was draus?>
<persons file="this">
    <!-- Hier beginnen die Daten -->
    <person id="p-11">
        <firstname>Mama</firstname>
        <lastname>Boye</lastname>
    </person>
    <person id="p-12">
        <firstname>Christopher</firstname>
        <lastname>Robin</lastname>
    </person>
    <person id="p-13">
        <firstname>Eule</firstname>
        <residence>Hundertsechzig-Morgen-Wald</residence>
    </person>
    <person id="p-14">
        <firstname>I-Ah</firstname>
    </person>
    <person id="p-15">
        <firstname>Kängah</firstname>
        <children>
            <person id="p-16" friends=" p-11 p-17 ">
                <firstname>Klein Ruh</firstname>
                <!-- Kommentar bei Klein Ruh -->
                <residence>Bei Kängah</residence>
            </person>
        </children>
        <residence>Bei Kängah</residence>
        <!-- zusätzlich -->
    </person>
    <person id="p-17">
        <firstname>Tieger</firstname>
        <residence>Bei Kängah</residence>
    </person>
    <person id="p-18" friends="p-15">
        <firstname>Ferkel<!-- Kommentar bei Ferkel--></firstname>
    </person>
    <!-- Kommentar zum Schluss -->
    <?tu was damit?>
</persons>
